package mcp

// Package mcp is the MCP (Model Context Protocol) client adapter layer.
//
// Position (anti-corruption layer boundary): a standalone adapter package alongside core/adapters/openai/.
// Only imports core + github.com/modelcontextprotocol/go-sdk (does not depend on the LLM anti-corruption
// layer). Adapts MCP server tools into core.Tool.
//
// capability: the MCP protocol does not carry ReadOnly/ConcurrencySafe, so defaults are fail-closed
// (not read-only, not concurrency-safe); config can declare per-tool overrides.

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/skys-mission/creator-agent/core"
)

// AdaptTools adapts a list of *mcp.Tool into a list of core.Tool.
//
// capability: defaults to fail-closed (not read-only, not concurrency-safe, MaxResultChars=20000);
// overrides declared in client.overrides take precedence.
func (c *Client) AdaptTools(tools []*mcp.Tool) []core.Tool {
	out := make([]core.Tool, 0, len(tools))
	for _, t := range tools {
		out = append(out, &adaptedTool{client: c, tool: t, schema: resolveInputSchema(t)})
	}
	return out
}

// resolveInputSchema converts a tool's input schema to JSON once, at adaptation time. The SDK exposes
// InputSchema as any (the default JSON marshaling of the server's schema, typically map[string]any);
// we marshal it back to JSON Schema bytes. A server that returns no usable schema falls back to a
// permissive default; the warning is emitted here (once per tool) rather than in Info(), which the
// agent loop calls repeatedly.
func resolveInputSchema(t *mcp.Tool) json.RawMessage {
	const defaultSchema = `{"type":"object"}`
	name := ""
	if t != nil {
		name = t.Name
	}
	if t == nil || t.InputSchema == nil {
		core.Warnf("mcp tool %q returned no usable input schema; using permissive default {\"type\":\"object\"}", name)
		return json.RawMessage(defaultSchema)
	}
	schema, err := json.Marshal(t.InputSchema)
	if err != nil || len(schema) == 0 || string(schema) == "null" {
		core.Warnf("mcp tool %q returned no usable input schema; using permissive default {\"type\":\"object\"}", name)
		return json.RawMessage(defaultSchema)
	}
	return json.RawMessage(schema)
}

// adaptedTool wraps a single *mcp.Tool as a core.Tool.
type adaptedTool struct {
	client *Client
	tool   *mcp.Tool
	schema json.RawMessage // input schema resolved once at adaptation (see resolveInputSchema)
}

func (a *adaptedTool) Info() core.ToolInfo {
	info := core.ToolInfo{
		Name:        a.tool.Name,
		Description: a.tool.Description,
		// fail-closed defaults: not read-only, not concurrency-safe
		MaxResultChars:    20000,
		InterruptBehavior: core.InterruptCancel,
		InputSchema:       a.schema,
	}
	// capability override
	if o, ok := a.client.override(a.tool.Name); ok {
		info.ReadOnly = o.ReadOnly
		info.ConcurrencySafe = o.ConcurrencySafe
		if o.MaxResultChars > 0 {
			info.MaxResultChars = o.MaxResultChars
		}
	}
	return info
}

func (a *adaptedTool) Exec(ctx context.Context, input json.RawMessage) (core.ToolResult, error) {
	// input is the JSON generated by the model (tool parameters); unmarshal into a map for MCP (MCP expects an args object)
	args := map[string]any{}
	if len(input) > 0 {
		if err := json.Unmarshal(input, &args); err != nil {
			return core.ToolResult{Content: fmt.Sprintf("invalid input: %v", err), IsError: true}, nil
		}
	}

	res, err := a.client.CallTool(ctx, a.tool.Name, args)
	if err != nil {
		return core.ToolResult{}, err
	}

	content := extractContent(res)
	result := core.ToolResult{Content: content, IsError: res.IsError}
	return result, nil
}

// extractContent concatenates CallToolResult.Content ([]mcp.Content) into a string.
//
// The SDK decodes every content element as a pointer (*TextContent, *ImageContent, ...), so the type
// switch matches pointer types. Text is concatenated; non-text uses a placeholder (core.ToolResult.Content
// is a string; multimedia left for V2).
func extractContent(res *mcp.CallToolResult) string {
	if res == nil || len(res.Content) == 0 {
		return ""
	}
	var sb strings.Builder
	for _, c := range res.Content {
		switch v := c.(type) {
		case *mcp.TextContent:
			sb.WriteString(v.Text)
		case *mcp.ImageContent:
			fmt.Fprintf(&sb, "[image: %s, %d bytes]", v.MIMEType, len(v.Data))
		case *mcp.AudioContent:
			fmt.Fprintf(&sb, "[audio: %s, %d bytes]", v.MIMEType, len(v.Data))
		default:
			// EmbeddedResource or unknown type: JSON fallback
			if data, err := json.Marshal(c); err == nil {
				sb.Write(data)
			} else {
				sb.WriteString(fmt.Sprintf("[unknown content: %T]", c))
			}
		}
		sb.WriteString("\n")
	}
	return strings.TrimRight(sb.String(), "\n")
}

// LoadAll connects all configured servers, fetches and adapts tools, and returns a core.Tool slice + a close function.
//
// Callers should invoke close() on program exit to clean up all connections.
// If any server connection fails: returns already-collected tools + error (best-effort, does not discard everything because one server failed).
func LoadAll(ctx context.Context, configs []ServerConfig) (tools []core.Tool, close func(), err error) {
	var clients []*Client
	closeFn := func() {
		for _, c := range clients {
			_ = c.Close()
		}
	}
	var firstErr error
	for _, cfg := range configs {
		c, e := NewClient(ctx, cfg)
		if e != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("mcp server %q: %w", cfg.Name, e)
			}
			continue
		}
		clients = append(clients, c)
		mcpTools, e := c.ListTools(ctx)
		if e != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("mcp server %q list tools: %w", cfg.Name, e)
			}
			continue
		}
		tools = append(tools, c.AdaptTools(mcpTools)...)
	}
	return tools, closeFn, firstErr
}
